name: lint & typecheck

on:
    push:
        branches: [main]
    pull_request:

jobs:
    checks:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run lint
              run: yarn -s lint --quiet

            - name: Run formatter check
              run: yarn -s format:check

            - name: Run typecheck
              run: yarn -s typecheck
